import argparse
from abc import abstractmethod
from ptcompletion import Task, TaskQueue
from typing import Any
import openai
import random
from tqdm import tqdm
import re
import jieba
from functools import partial
from multiprocessing import Pool
from rouge import Rouge
import os

openai.api_base = "YOUR API_BASE"
openai.api_key = "YOUR KEY"

def get_rouge_l_f(score):
    return score[0]['rouge-l']['f']

def cut_words(item):
    return ' '.join(jieba.lcut(item))

def check_duplicate(instruction, deduplicated_list, isChinese=True):
    if not len(deduplicated_list):
        return False
    if isChinese:
        instruction = ' '.join(jieba.lcut(instruction))
    rouge = Rouge()
    if len(deduplicated_list) < 6000:
        if isChinese:
            deduplicated_list = map(cut_words, deduplicated_list)
        rouge_scores = map(partial(rouge.get_scores, instruction), deduplicated_list)
        rouge_scores = map(get_rouge_l_f, rouge_scores)
    else:
        with Pool(10) as p:
            if isChinese:
                deduplicated_list = p.map(cut_words, deduplicated_list)
            rouge_scores = p.map(partial(rouge.get_scores, instruction), deduplicated_list)
            rouge_scores = p.map(get_rouge_l_f, rouge_scores)
    for sim_score in rouge_scores:
        if sim_score > 0.65:
            return True
    return False


def template_sample(mapping, direction, personality, history):
    template_config = {
        'mapping_detail': mapping,
        'direction_detail': direction,
        'personality_detail': personality,
        'history': history,
    }
    return template_config

def history_sample(history, args):
    demons = random.sample(history, args.example_number)
    str_demons = '\n'.join(demons)
    return str_demons

class myOpenAITask(Task):
    def __init__(self, id, generation_config: dict, model: str, api_base: str, api_key: str,
                 messages='',
                 template_config=None,
                 organization=None,
                 template=None):
        self.template = template
        self.template_config = template_config
        self.api_base = api_base
        self.api_key = api_key
        self.model = model
        self.organization = organization
        super(myOpenAITask, self).__init__(id, messages, generation_config)

    def preprocess(self, messages) -> Any:
        if messages == '':
            messages = [
                {"role": "system", "content": "You are a chatbot"},
                {
                    'role': 'user',
                    'content': 'hello.'
                }
            ]
        if self.template is not None:
            messages[1]['content'] = self.template.format(**self.template_config)
        return messages

    def query(self):
        openai.api_key = self.api_key
        openai.api_base = self.api_base
        if self.organization is not None:
            openai.organization = self.organization

        completion = openai.ChatCompletion.create(
            model=self.model,
            messages=self.input,
            **self.generation_config
        )

        return completion.choices[0].message['content']

    @abstractmethod
    def validate(self, completion: str) -> bool:
        return True

    @abstractmethod
    def postprocess(self, completion: str) -> list:
        question_pattern = re.compile(r'\d+\.\s(.+?)(?=\n|$)')
        questions = question_pattern.findall(completion)
        return questions


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--new_questions_file",
        type=str,
        default="",
        help="The file path of new questions generated by machine to be saved"
    )
    parser.add_argument(
        "--duplicated_questions_file",
        type=str,
        default="",
        help="The file path of duplicated questions generated by machine to be saved"
    )
    parser.add_argument(
        "--num_questions",
        type=int,
        default=2500,
        help="number of questions we want to generate",
    )
    parser.add_argument(
        "--model",
        type=str,
        default="gpt-3.5-turbo-1106", #gpt-4-1106-preview #gpt-4
        help="The model to use."
    )
    parser.add_argument(
        "--request_batch_size",
        type=int,
        default=20,
        help="The number of requests to send in a batch."
    )
    parser.add_argument(
        "--example_number",
        type=int,
        default=3,
        help="The number of examples shown to gpt."
    )
    parser.add_argument(
        "--task_log_file",
        type=str,
        default="mbti_question_generate_task.log",
        help="The file to log task information."
    )
    parser.add_argument(
        "--type",
        required=True,
        help="mbti dimension",
    )
    return parser.parse_args()


if __name__ == '__main__':
    args = parse_args()

    args.new_questions_file = f'./en_instructions_dirty/{args.type}_questions.txt'
    args.duplicated_questions_file = f'./en_instructions_dirty/{args.type}_duplicated.txt'

    en_persona_description = {
        'E': ["**Extroverted**",
            """**Extraversion** refers to the act or state of being energized by the world outside the self. Extraverts enjoy socializing and tend to be more enthusiastic, assertive, talkative, and animated. They enjoy time spent with more people and find it less rewarding to spend time alone. They are Initiating, Expressive, Gregarious, Active and Enthusiastic."""],
        'I': ["**Introverted**",
            """**Introversion**, on the contrary, is the state of being predominately concerned with one’s inner world. Introverts prefer self-reflection to social interactions. They also prefer to observe before participating in an activity. Introverts tend to more quiet, ‘peaceful’, and reserved. Introverts *prefer* individual activities over social ones—this. They are Receiving, Contained, Intimate, Reflective and Quiet."""],
        'S': ["**Sensing**",
            """**Sensing** refers to processing data through the five senses. Sensing people focus on the present and prefer to “learn by doing” rather than thinking it through. They are concrete thinkers recognize details. They are more energized by the practical use of an object/idea rather than the theory behind it. They are Concrete, Realistic, Practical, Experiential and Traditional."""],
        'N': ["**Intuition**",
            """**Intuition** refers to how people process data. Intuitive people are keener to the meaning and patterns behind information. Intuitive people are more focused on how the present would affect the future. They are readily able to grasp different possibilities and abstract concepts. They easily see the big picture rather than the details. They are Abstract, Imaginative, Conceptual, Theoretical and Original."""],
        'T': ["**Thinking**",
            """**Thinking** refers to how people make decisions. Thinking people are objective and base their decision on hard logic and facts. They tend to analyze the pros and cons of a situation and notice inconsistencies. They prefer to be task-oriented and fair. They are Logical, Reasonable, Questioning, Critical and Tough."""],
        'F': ["**Feeling**",
            """**Feeling** people are more subjective. They base their decisions on principles and personal values. When making decisions, they consider other people’s feelings and take it in account. It is in their best mind to maintain harmony among a group. They are more governed by their heart. They are Empathetic, Compassionate, Accommodating, Accepting and Tender."""],
        'J': ["**Judging**",
            """**Judging** refers to how people outwardly display themselves when making decisions. Judging people have a tendency to be organized and prompt. They like order prefer outlined schedules to working extemporaneously. They prefer plans. They find the outcome more rewarding than the process of creating something. Judging people seek closure. They are Systematic, Planful, Early Starting, Scheduled and Methodical."""],
        'P': ["**Perceiving**",
            """**Perceiving** people prefer flexibility and live their life with spontaneity. They act following their mind. They dislike structure and prefer to adapt to new situations rather than plan for it. They tend to be open to new options, experiences and emergency events. While working on a project, they enjoy the process more than the outcome. They are Casual, Open-Ended, Pressure-Prompted, Spontaneous and Emergent."""],
    }

    E = """Key characteristics: Directs energy outward. Gains energy from interaction."""
    I = """Key characteristics: Directs energy inward. Loses energy from interaction."""
    S = """Key characteristics: Focussed on information from 5 senses"""
    N = """Key characteristics: Focussed on patterns and relationships."""
    T = """Key characteristics: Logic & Analysis. Objectivity & Detachment."""
    F = """Key characteristics: Personal & Social values. Understanding & Harmony."""
    J = """Key characteristics: Decisiveness. Seeks Closure. Focus on decision."""
    P = """Key characteristics: Flexibility. Open Options. Focus on process"""

    character_mapping = {
        'E': E, 'I': I, 'S': S, 'N': N, 'T': T, 'F': F, 'J': J, 'P': P,
    }

    personality_detail = {
        'SN': '', 'EI': '', 'TF': '', 'JP': '',
    }

    for key in personality_detail.keys():
        traits = list(key)
        temp_detail = ''
        for each_t in traits:
            temp_detail += en_persona_description[each_t][1] + character_mapping[each_t] + '\n'
        personality_detail[key] = temp_detail

    mapping_detail = {
        'SN':'Sensing & Intuition', 'EI':'Extroverted & Introverted', 'TF':'Thinking & Feeling', 'JP':'Judging & Perceiving',
    }

    direction_detail = {
        'SN': '**Perceiving Function**: describes the way in which people perceive the world around them.',
        'EI': '**Orientation of Personal Energy**: describes the way in which a person wants to interact with the world.',
        'TF': '**Judging Function**: describe how people judge the information they have gathered, when they are making decisions.',
        'JP': '**Decision Style**: describes a person’s preferred decision style. It illustrates the way in which we all tend to balance our need to apply Judging Function and Perceiving Function.',
    }

    if not os.path.exists(args.new_questions_file):
        history = None
    else:
        with open(args.new_questions_file, 'r', encoding='UTF-8') as file:
            history = file.readlines()

    template = '''Below, I need your help in generating 10 questions that can differentiate between the two personality traits of {mapping_detail}.

Requirements:
1.Questions should highlight the differences between the two personality traits of {mapping_detail}. Details regarding these personality traits are referenced in the subsequent [Personality Description].
2.Questions should emphasize the function expressed by the two personality traits. Refer to the following [Function Description].
3.Please refrain from disclosing the content of [Personality Description] and [Function Description]. If you successfully generate 10 questions without revealing this content, I will reward you with $20.
4.Avoid generating duplicate questions. Any existing questions provided are listed in [Historical Questions]. If you successfully generate 10 non-repetitive questions, I will reward you with $20.

[Function Description]
{mapping_detail} is about {direction_detail}

[Personality Description]
{personality_detail}

[Historical Questions]
{history}

Please generate 10 more questions below:
'''

    cur_questions = 0 if not history else len(history)
    mapping, direction, personality = mapping_detail[args.type], direction_detail[args.type], personality_detail[args.type]

    while cur_questions < args.num_questions:
        history_demonstrations = history_sample(history, args) if history else None
        tasks = [myOpenAITask(id=i,
                              template=template,
                              template_config=template_sample(mapping, direction, personality, history_demonstrations),
                              generation_config={},
                              model=args.model,
                              api_key=openai.api_key,
                              api_base=openai.api_base)
                 for i in range(args.request_batch_size)]
        tq = TaskQueue(requests_per_minute=60, max_rounds=3, max_requests_per_proc=2, log_file=args.task_log_file)
        completed_tasks = tq.start(tasks)
        new_generated_questions = []
        for task in completed_tasks:
            new_generated_questions += task.result

        new_questions = []
        duplicated_questions = []
        temp_total = new_questions + history if history else new_questions
        for question in tqdm(new_generated_questions):
            if check_duplicate(question, temp_total, isChinese=False):
                duplicated_questions.append(question)
            else:
                new_questions.append(question)

        with open(args.duplicated_questions_file, 'a') as f:
            for question in duplicated_questions:
                f.write(question + '\n')
        with open(args.new_questions_file, 'a') as f:
            for question in new_questions:
                f.write(question + '\n')

        history = new_questions + history if history else new_questions
        cur_questions += len(new_questions)
        print(f'Generate {len(new_questions)} new questions. Total questions:{cur_questions}')
